### ISSUE TITLE
ArrayIndexOutOfBoundsException when rightclicking crushing vat

### ISSUE THREAD

**Issue by MasterEnderman** [The-Acronym-Coders/Survivalism#19]
Survivalism: 1.0.0
Forge: 14.23.5.2815
BASE: 3.11.1
Crash-Report: https://paste.dimdev.org/qexelalayi.mccrash

**Comment by Lanse505** [comment]
1) What the actual fluff O.o that's a high negative numbers
2) I'm gonna be looking into this over the weekend hopefully

**Comment by Lanse505** [comment]
Found the issue most likely, gonna be poking the dev who caused this with this :P 
Hopefully, there will be a new build to fix this soon(TM).

I'll update this issue once something new comes up.

**Comment by Lanse505** [comment]
Do me a favor and try this build:
@MasterEnderman 
https://ci.blamejared.com/job/Survivalism/job/develop%252F1.12.2/

**Comment by Lanse505** [comment]
So from testing with a few other people this should have resolved the issue, new build on CF
