### ISSUE TITLE
Soaking Barrel collects water in desert while it's raining

### ISSUE THREAD

**Issue by MasterEnderman** [The-Acronym-Coders/Survivalism#22]
if it doesn't rain in a biom the barrel shouldn't collect water.
tested in vanilla deserts as well as traverse arid highlands.

**Comment by MasterEnderman** [comment]
Maybe you even could add a config to disable collecting rain water in general?

**Comment by Lanse505** [comment]
1) Fixed in an upcoming update
2) Yea I can add a config option to disable that.

**Comment by Lanse505** [comment]
Added a config option and fixed the raining in deserts bug.
New release has been pushed to CF
