### ISSUE TITLE
Soaking + Storage Barrel not displaying amount of fluid

### ISSUE THREAD

**Issue by SeriousCreeper** [The-Acronym-Coders/Survivalism#28]
Heya,

i noticed the soaking and storage barrels don't show the amount of liquid when hovering over the fluid bar. The Soaking barrel shows what type of fluid, but no value. The storage barrel doesn't show anything (not even what fluid it is). 

Cheers,
SC

**Comment by Lanse505** [comment]
This is fixed in-dev
